// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package db

import (
	"context"
	"database/sql"
)

const countMessagesBySession = `-- name: CountMessagesBySession :one
SELECT COUNT(*)
FROM messages
WHERE session_id = ?
`

func (q *Queries) CountMessagesBySession(ctx context.Context, sessionID string) (int64, error) {
	row := q.queryRow(ctx, q.countMessagesBySessionStmt, countMessagesBySession, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
    id,
    session_id,
    role,
    parts,
    model,
    provider,
    reasoning_effort,
    is_summary_message,
    hidden,
    auto_resumed,
    background_job_notice,
    created_at,
    updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, strftime('%s', 'now'), strftime('%s', 'now')
)
RETURNING id, session_id, role, parts, model, created_at, updated_at, finished_at, provider, is_summary_message, pinned, hidden, reasoning_effort, auto_resumed, background_job_notice
`

type CreateMessageParams struct {
	ID                  string         `json:"id"`
	SessionID           string         `json:"session_id"`
	Role                string         `json:"role"`
	Parts               string         `json:"parts"`
	Model               sql.NullString `json:"model"`
	Provider            sql.NullString `json:"provider"`
	ReasoningEffort     sql.NullString `json:"reasoning_effort"`
	IsSummaryMessage    int64          `json:"is_summary_message"`
	Hidden              int64          `json:"hidden"`
	AutoResumed         int64          `json:"auto_resumed"`
	BackgroundJobNotice int64          `json:"background_job_notice"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.queryRow(ctx, q.createMessageStmt, createMessage,
		arg.ID,
		arg.SessionID,
		arg.Role,
		arg.Parts,
		arg.Model,
		arg.Provider,
		arg.ReasoningEffort,
		arg.IsSummaryMessage,
		arg.Hidden,
		arg.AutoResumed,
		arg.BackgroundJobNotice,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Parts,
		&i.Model,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.Provider,
		&i.IsSummaryMessage,
		&i.Pinned,
		&i.Hidden,
		&i.ReasoningEffort,
		&i.AutoResumed,
		&i.BackgroundJobNotice,
	)
	return i, err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM messages
WHERE id = ?
`

func (q *Queries) DeleteMessage(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteMessageStmt, deleteMessage, id)
	return err
}

const deleteSessionMessages = `-- name: DeleteSessionMessages :exec
DELETE FROM messages
WHERE session_id = ?
`

func (q *Queries) DeleteSessionMessages(ctx context.Context, sessionID string) error {
	_, err := q.exec(ctx, q.deleteSessionMessagesStmt, deleteSessionMessages, sessionID)
	return err
}

const getMessage = `-- name: GetMessage :one
SELECT id, session_id, role, parts, model, created_at, updated_at, finished_at, provider, is_summary_message, pinned, hidden, reasoning_effort, auto_resumed, background_job_notice
FROM messages
WHERE id = ? LIMIT 1
`

func (q *Queries) GetMessage(ctx context.Context, id string) (Message, error) {
	row := q.queryRow(ctx, q.getMessageStmt, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Parts,
		&i.Model,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.Provider,
		&i.IsSummaryMessage,
		&i.Pinned,
		&i.Hidden,
		&i.ReasoningEffort,
		&i.AutoResumed,
		&i.BackgroundJobNotice,
	)
	return i, err
}

const listAllUserMessages = `-- name: ListAllUserMessages :many
SELECT id, session_id, role, parts, model, created_at, updated_at, finished_at, provider, is_summary_message, pinned, hidden, reasoning_effort, auto_resumed, background_job_notice
FROM messages
WHERE role = 'user'
ORDER BY created_at DESC, rowid DESC
`

// rowid is the tie-breaker: see ListUserMessagesBySession above - identical
// reasoning applies across all sessions, not just one.
func (q *Queries) ListAllUserMessages(ctx context.Context) ([]Message, error) {
	rows, err := q.query(ctx, q.listAllUserMessagesStmt, listAllUserMessages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Parts,
			&i.Model,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
			&i.Provider,
			&i.IsSummaryMessage,
			&i.Pinned,
			&i.Hidden,
			&i.ReasoningEffort,
			&i.AutoResumed,
			&i.BackgroundJobNotice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesBySession = `-- name: ListMessagesBySession :many
SELECT id, session_id, role, parts, model, created_at, updated_at, finished_at, provider, is_summary_message, pinned, hidden, reasoning_effort, auto_resumed, background_job_notice
FROM messages
WHERE session_id = ?
ORDER BY created_at ASC, rowid ASC
`

// rowid is the tie-breaker: created_at is stored in SECONDS, so a single agent
// turn produces dozens of rows with an identical created_at. Without a total
// order SQLite does not guarantee a stable order among those ties. This is the
// same class of bug fixed for ListMessagesBySessionPaginated (see its comment
// below) - here applied to the oldest-first, non-paginated variant, so
// (created_at ASC, rowid ASC) is a deterministic oldest-first total order.
// rowid is SQLite's implicit monotonic insertion counter (messages.id is a
// non-monotonic UUID, unsuitable as a tiebreaker).
func (q *Queries) ListMessagesBySession(ctx context.Context, sessionID string) ([]Message, error) {
	rows, err := q.query(ctx, q.listMessagesBySessionStmt, listMessagesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Parts,
			&i.Model,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
			&i.Provider,
			&i.IsSummaryMessage,
			&i.Pinned,
			&i.Hidden,
			&i.ReasoningEffort,
			&i.AutoResumed,
			&i.BackgroundJobNotice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesBySessionPaginated = `-- name: ListMessagesBySessionPaginated :many
SELECT id, session_id, role, parts, model, created_at, updated_at, finished_at, provider, is_summary_message, pinned, hidden, reasoning_effort, auto_resumed, background_job_notice
FROM messages
WHERE session_id = ?
ORDER BY created_at DESC, rowid DESC
LIMIT ? OFFSET ?
`

type ListMessagesBySessionPaginatedParams struct {
	SessionID string `json:"session_id"`
	Limit     int64  `json:"limit"`
	Offset    int64  `json:"offset"`
}

// rowid is the tie-breaker: created_at is stored in SECONDS, so a single agent
// turn produces dozens of rows with an identical created_at. Without a total
// order SQLite does not guarantee a stable order among those ties, which makes
// OFFSET pagination lose/duplicate rows when the query plan shifts between
// page fetches. rowid is SQLite's implicit monotonic insertion counter, so
// (created_at DESC, rowid DESC) is a deterministic newest-first total order.
func (q *Queries) ListMessagesBySessionPaginated(ctx context.Context, arg ListMessagesBySessionPaginatedParams) ([]Message, error) {
	rows, err := q.query(ctx, q.listMessagesBySessionPaginatedStmt, listMessagesBySessionPaginated, arg.SessionID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Parts,
			&i.Model,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
			&i.Provider,
			&i.IsSummaryMessage,
			&i.Pinned,
			&i.Hidden,
			&i.ReasoningEffort,
			&i.AutoResumed,
			&i.BackgroundJobNotice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserMessagesBySession = `-- name: ListUserMessagesBySession :many
SELECT id, session_id, role, parts, model, created_at, updated_at, finished_at, provider, is_summary_message, pinned, hidden, reasoning_effort, auto_resumed, background_job_notice
FROM messages
WHERE session_id = ? AND role = 'user'
ORDER BY created_at DESC, rowid DESC
`

// rowid is the tie-breaker: created_at is stored in SECONDS, so multiple user
// messages within the same second (e.g. rapid follow-ups) are not given a
// stable order by created_at alone. Same class of bug fixed for
// ListMessagesBySession/ListMessagesBySessionPaginated - rowid is SQLite's
// implicit monotonic insertion counter (messages.id is a non-monotonic UUID,
// unsuitable as a tiebreaker), so (created_at DESC, rowid DESC) is a
// deterministic newest-first total order.
func (q *Queries) ListUserMessagesBySession(ctx context.Context, sessionID string) ([]Message, error) {
	rows, err := q.query(ctx, q.listUserMessagesBySessionStmt, listUserMessagesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Parts,
			&i.Model,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
			&i.Provider,
			&i.IsSummaryMessage,
			&i.Pinned,
			&i.Hidden,
			&i.ReasoningEffort,
			&i.AutoResumed,
			&i.BackgroundJobNotice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMessage = `-- name: UpdateMessage :exec
UPDATE messages
SET
    parts = ?,
    finished_at = ?,
    updated_at = strftime('%s', 'now')
WHERE id = ?
`

type UpdateMessageParams struct {
	Parts      string        `json:"parts"`
	FinishedAt sql.NullInt64 `json:"finished_at"`
	ID         string        `json:"id"`
}

func (q *Queries) UpdateMessage(ctx context.Context, arg UpdateMessageParams) error {
	_, err := q.exec(ctx, q.updateMessageStmt, updateMessage, arg.Parts, arg.FinishedAt, arg.ID)
	return err
}

const updateMessagePinned = `-- name: UpdateMessagePinned :exec
UPDATE messages
SET
    pinned = ?,
    updated_at = strftime('%s', 'now')
WHERE id = ?
`

type UpdateMessagePinnedParams struct {
	Pinned int64  `json:"pinned"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateMessagePinned(ctx context.Context, arg UpdateMessagePinnedParams) error {
	_, err := q.exec(ctx, q.updateMessagePinnedStmt, updateMessagePinned, arg.Pinned, arg.ID)
	return err
}
