// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orphan_outbox.sql

package db

import (
	"context"
)

const deleteOrphanOutboxEntryIfPending = `-- name: DeleteOrphanOutboxEntryIfPending :execrows
DELETE FROM orphan_call_outbox
WHERE id = ? AND status = 'pending'
`

// Delete an orphan outbox entry only if it's still pending (for atomic drain).
// Returns the number of rows deleted (0 or 1).
// Used by DrainOrphanOutboxEntry to atomically move entries to the main queue.
func (q *Queries) DeleteOrphanOutboxEntryIfPending(ctx context.Context, id string) (int64, error) {
	result, err := q.exec(ctx, q.deleteOrphanOutboxEntryIfPendingStmt, deleteOrphanOutboxEntryIfPending, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getOrphanOutboxEntry = `-- name: GetOrphanOutboxEntry :one
SELECT id, session_id, call_data, status, attempts, max_attempts, last_error, created_at, updated_at
FROM orphan_call_outbox
WHERE id = ?
`

// Get a single entry by ID.
func (q *Queries) GetOrphanOutboxEntry(ctx context.Context, id string) (OrphanCallOutbox, error) {
	row := q.queryRow(ctx, q.getOrphanOutboxEntryStmt, getOrphanOutboxEntry, id)
	var i OrphanCallOutbox
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.CallData,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingOrphanOutboxEntries = `-- name: ListPendingOrphanOutboxEntries :many
SELECT id, session_id, call_data, status, attempts, max_attempts, last_error, created_at, updated_at
FROM orphan_call_outbox
WHERE status = 'pending'
ORDER BY created_at ASC
`

// Get all pending outbox entries for recovery (scanned by pump).
func (q *Queries) ListPendingOrphanOutboxEntries(ctx context.Context) ([]OrphanCallOutbox, error) {
	rows, err := q.query(ctx, q.listPendingOrphanOutboxEntriesStmt, listPendingOrphanOutboxEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrphanCallOutbox{}
	for rows.Next() {
		var i OrphanCallOutbox
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.CallData,
			&i.Status,
			&i.Attempts,
			&i.MaxAttempts,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const writeToOrphanOutbox = `-- name: WriteToOrphanOutbox :one

INSERT INTO orphan_call_outbox (
    id,
    session_id,
    call_data,
    status,
    attempts,
    max_attempts,
    created_at,
    updated_at
) VALUES (?, ?, ?, 'pending', 0, 5, ?, ?)
RETURNING id, session_id, call_data, status, attempts, max_attempts, last_error, created_at, updated_at
`

type WriteToOrphanOutboxParams struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
	CallData  string `json:"call_data"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

// Task #340's original claim/mark-done/mark-failed/release-for-retry model
// (ClaimOrphanOutboxEntry, MarkOrphanOutboxEntryDone, MarkOrphanOutboxEntryFailed,
// ReleaseOrphanOutboxEntryForRetry, CleanupOldDoneOrphanOutboxEntries) was
// superseded by task #426's atomic DrainOrphanOutboxEntry (single
// insert-to-main-queue + delete-from-outbox transaction, no intermediate
// 'processing'/'done'/'failed' state to get stuck in). Removed as dead
// code -- task #440 follow-up decision: a genuinely malformed,
// never-enqueueable entry now retries every drain tick forever instead of
// reaching a terminal 'failed' state. Accepted deliberately rather than
// reintroducing attempts-tracking into the atomic transaction: the FK
// ON DELETE CASCADE on session_id already closes the realistic failure
// mode (session deleted -> row cascades away on its own); what's left is
// an operationally-visible (slog.Error per tick), not silent, edge case
// for data that was malformed from the start. `attempts`/`max_attempts`/
// `status` values other than 'pending' are consequently unreachable going
// forward but left in the schema rather than a migration for this.
// Write a call to the orphan outbox when main run queue enqueue fails.
// Returns the outbox row (or error on write failure).
func (q *Queries) WriteToOrphanOutbox(ctx context.Context, arg WriteToOrphanOutboxParams) (OrphanCallOutbox, error) {
	row := q.queryRow(ctx, q.writeToOrphanOutboxStmt, writeToOrphanOutbox,
		arg.ID,
		arg.SessionID,
		arg.CallData,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i OrphanCallOutbox
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.CallData,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
