// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orphan_outbox.sql

package db

import (
	"context"
	"database/sql"
)

const claimOrphanOutboxEntry = `-- name: ClaimOrphanOutboxEntry :one
UPDATE orphan_call_outbox
SET status = 'processing',
    attempts = attempts + 1,
    updated_at = ?
WHERE id = ? AND status = 'pending'
RETURNING id, session_id, call_data, status, attempts, max_attempts, last_error, created_at, updated_at
`

type ClaimOrphanOutboxEntryParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

// Atomically claim a pending entry for processing (move to processing state).
// Used by pump when moving an entry to the main run queue.
func (q *Queries) ClaimOrphanOutboxEntry(ctx context.Context, arg ClaimOrphanOutboxEntryParams) (OrphanCallOutbox, error) {
	row := q.queryRow(ctx, q.claimOrphanOutboxEntryStmt, claimOrphanOutboxEntry, arg.UpdatedAt, arg.ID)
	var i OrphanCallOutbox
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.CallData,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const cleanupOldDoneOrphanOutboxEntries = `-- name: CleanupOldDoneOrphanOutboxEntries :exec
DELETE FROM orphan_call_outbox
WHERE status = 'done' AND updated_at < ?
`

// Clean up old done entries (optional, for housekeeping).
func (q *Queries) CleanupOldDoneOrphanOutboxEntries(ctx context.Context, updatedAt int64) error {
	_, err := q.exec(ctx, q.cleanupOldDoneOrphanOutboxEntriesStmt, cleanupOldDoneOrphanOutboxEntries, updatedAt)
	return err
}

const getOrphanOutboxEntry = `-- name: GetOrphanOutboxEntry :one
SELECT id, session_id, call_data, status, attempts, max_attempts, last_error, created_at, updated_at
FROM orphan_call_outbox
WHERE id = ?
`

// Get a single entry by ID.
func (q *Queries) GetOrphanOutboxEntry(ctx context.Context, id string) (OrphanCallOutbox, error) {
	row := q.queryRow(ctx, q.getOrphanOutboxEntryStmt, getOrphanOutboxEntry, id)
	var i OrphanCallOutbox
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.CallData,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingOrphanOutboxEntries = `-- name: ListPendingOrphanOutboxEntries :many
SELECT id, session_id, call_data, status, attempts, max_attempts, last_error, created_at, updated_at
FROM orphan_call_outbox
WHERE status = 'pending'
ORDER BY created_at ASC
`

// Get all pending outbox entries for recovery (scanned by pump).
func (q *Queries) ListPendingOrphanOutboxEntries(ctx context.Context) ([]OrphanCallOutbox, error) {
	rows, err := q.query(ctx, q.listPendingOrphanOutboxEntriesStmt, listPendingOrphanOutboxEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrphanCallOutbox{}
	for rows.Next() {
		var i OrphanCallOutbox
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.CallData,
			&i.Status,
			&i.Attempts,
			&i.MaxAttempts,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOrphanOutboxEntryDone = `-- name: MarkOrphanOutboxEntryDone :execrows
DELETE FROM orphan_call_outbox
WHERE id = ? AND status = 'processing'
`

// Mark an entry as done (successfully moved to main run queue).
func (q *Queries) MarkOrphanOutboxEntryDone(ctx context.Context, id string) (int64, error) {
	result, err := q.exec(ctx, q.markOrphanOutboxEntryDoneStmt, markOrphanOutboxEntryDone, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markOrphanOutboxEntryFailed = `-- name: MarkOrphanOutboxEntryFailed :one
UPDATE orphan_call_outbox
SET status = 'failed',
    last_error = ?,
    updated_at = ?
WHERE id = ? AND status = 'processing'
RETURNING id, session_id, call_data, status, attempts, max_attempts, last_error, created_at, updated_at
`

type MarkOrphanOutboxEntryFailedParams struct {
	LastError sql.NullString `json:"last_error"`
	UpdatedAt int64          `json:"updated_at"`
	ID        string         `json:"id"`
}

// Mark an entry as failed (exhausted retries or persistent error).
func (q *Queries) MarkOrphanOutboxEntryFailed(ctx context.Context, arg MarkOrphanOutboxEntryFailedParams) (OrphanCallOutbox, error) {
	row := q.queryRow(ctx, q.markOrphanOutboxEntryFailedStmt, markOrphanOutboxEntryFailed, arg.LastError, arg.UpdatedAt, arg.ID)
	var i OrphanCallOutbox
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.CallData,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const writeToOrphanOutbox = `-- name: WriteToOrphanOutbox :one
INSERT INTO orphan_call_outbox (
    id,
    session_id,
    call_data,
    status,
    attempts,
    max_attempts,
    created_at,
    updated_at
) VALUES (?, ?, ?, 'pending', 0, 5, ?, ?)
RETURNING id, session_id, call_data, status, attempts, max_attempts, last_error, created_at, updated_at
`

type WriteToOrphanOutboxParams struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
	CallData  string `json:"call_data"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

// Write a call to the orphan outbox when main run queue enqueue fails.
// Returns the outbox row (or error on write failure).
func (q *Queries) WriteToOrphanOutbox(ctx context.Context, arg WriteToOrphanOutboxParams) (OrphanCallOutbox, error) {
	row := q.queryRow(ctx, q.writeToOrphanOutboxStmt, writeToOrphanOutbox,
		arg.ID,
		arg.SessionID,
		arg.CallData,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i OrphanCallOutbox
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.CallData,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
