// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permissions.sql

package db

import (
	"context"
)

const createSessionPermission = `-- name: CreateSessionPermission :exec
INSERT INTO session_permissions (id, session_id, tool_name, action, path, enabled)
VALUES (?, ?, ?, ?, ?, 1)
ON CONFLICT(session_id, tool_name, action, path) DO NOTHING
`

type CreateSessionPermissionParams struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
	ToolName  string `json:"tool_name"`
	Action    string `json:"action"`
	Path      string `json:"path"`
}

// ON CONFLICT DO NOTHING relies on idx_session_permissions_uniq from
// migration 20260517000001. Without it a repeated Always-Allow click
// on the same (session, tool, action, path) tuple would create a fresh
// row instead of being a no-op. Re-enabling a disabled-then-regranted
// rule is handled explicitly via UpdatePermissionEnabled, not here.
func (q *Queries) CreateSessionPermission(ctx context.Context, arg CreateSessionPermissionParams) error {
	_, err := q.exec(ctx, q.createSessionPermissionStmt, createSessionPermission,
		arg.ID,
		arg.SessionID,
		arg.ToolName,
		arg.Action,
		arg.Path,
	)
	return err
}

const deletePermission = `-- name: DeletePermission :exec
DELETE FROM session_permissions
WHERE id = ?
`

func (q *Queries) DeletePermission(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deletePermissionStmt, deletePermission, id)
	return err
}

const listAllSessionPermissions = `-- name: ListAllSessionPermissions :many
SELECT id, session_id, tool_name, action, path, created_at, enabled
FROM session_permissions
`

func (q *Queries) ListAllSessionPermissions(ctx context.Context) ([]SessionPermission, error) {
	rows, err := q.query(ctx, q.listAllSessionPermissionsStmt, listAllSessionPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionPermission{}
	for rows.Next() {
		var i SessionPermission
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ToolName,
			&i.Action,
			&i.Path,
			&i.CreatedAt,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionPermissions = `-- name: ListSessionPermissions :many
SELECT id, session_id, tool_name, action, path, created_at, enabled
FROM session_permissions
WHERE session_id = ?
`

func (q *Queries) ListSessionPermissions(ctx context.Context, sessionID string) ([]SessionPermission, error) {
	rows, err := q.query(ctx, q.listSessionPermissionsStmt, listSessionPermissions, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionPermission{}
	for rows.Next() {
		var i SessionPermission
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ToolName,
			&i.Action,
			&i.Path,
			&i.CreatedAt,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const matchSessionPermission = `-- name: MatchSessionPermission :one
SELECT id
FROM session_permissions
WHERE enabled = 1
  AND tool_name = ?
  AND action = ?
  AND path = ?
  AND (session_id = '' OR session_id = ?)
LIMIT 1
`

type MatchSessionPermissionParams struct {
	ToolName  string `json:"tool_name"`
	Action    string `json:"action"`
	Path      string `json:"path"`
	SessionID string `json:"session_id"`
}

// Returns the row id of an enabled "always allow" rule that matches the
// given (sessionID, toolName, action, path) tuple, or sql.ErrNoRows.
// session_id is empty for global rules; we accept either empty or the
// exact session_id so the same query handles both.
func (q *Queries) MatchSessionPermission(ctx context.Context, arg MatchSessionPermissionParams) (string, error) {
	row := q.queryRow(ctx, q.matchSessionPermissionStmt, matchSessionPermission,
		arg.ToolName,
		arg.Action,
		arg.Path,
		arg.SessionID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const updatePermissionEnabled = `-- name: UpdatePermissionEnabled :exec
UPDATE session_permissions
SET enabled = ?
WHERE id = ?
`

type UpdatePermissionEnabledParams struct {
	Enabled int64  `json:"enabled"`
	ID      string `json:"id"`
}

func (q *Queries) UpdatePermissionEnabled(ctx context.Context, arg UpdatePermissionEnabledParams) error {
	_, err := q.exec(ctx, q.updatePermissionEnabledStmt, updatePermissionEnabled, arg.Enabled, arg.ID)
	return err
}
