// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	// Mark a leased entry as successfully completed (terminal).
	// Removes it from the queue (acked is terminal, no longer needed).
	// Scoped to the current lease owner (found by the fifth @oh review pass over
	// #337-349): without this, an executor that lost its lease to a
	// CleanupExpiredLeases recovery (a rare residual now that executeEntry
	// renews its lease for the duration of a real turn, but not impossible
	// under a pathological scheduling stall) could Ack a row a DIFFERENT,
	// currently-live executor now owns, deleting work out from under it.
	AckRunQueueEntry(ctx context.Context, arg AckRunQueueEntryParams) (string, error)
	// Reset stale leased entries back to pending (lease expiry recovery).
	// Run periodically to recover from crashed pump instances.
	// Increments attempts: a lease that expired without a matching Ack/Nack
	// means whatever was executing it (a pump process, a goroutine) died or
	// hung mid-execution without ever completing a normal outcome. Without
	// counting this as an attempt, a poison entry whose execution always
	// kills the process before it can Ack or Nack would accumulate attempts=0
	// forever and never reach RunQueueMaxAttempts, looping indefinitely
	// instead of eventually being dead-lettered.
	CleanupExpiredLeases(ctx context.Context, arg CleanupExpiredLeasesParams) error
	CountMessagesBySession(ctx context.Context, sessionID string) (int64, error)
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	// pending_injects is the cross-process inject queue for `crush sessions
	// inject`. See migration 20260703000001 for the full semantics.
	//
	// NOTE: as of this fork the session-layer wrapper (session.go
	// DrainPendingInjects / CreatePendingInject) talks to this table via raw
	// database/sql, matching the existing cross-process signal pattern
	// (RequestCancel / SetBudget). These sqlc-generated methods below ARE
	// wired into db.go's Prepare/Close/WithTx (as of the sqlc regeneration
	// that added call_tree_activity.sql), but nothing in the codebase calls
	// them yet - session.go's raw-SQL path remains the actual implementation.
	// Keep both in sync if pending_injects' schema changes.
	CreatePendingInject(ctx context.Context, arg CreatePendingInjectParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// ON CONFLICT DO NOTHING relies on idx_session_permissions_uniq from
	// migration 20260517000001. Without it a repeated Always-Allow click
	// on the same (session, tool, action, path) tuple would create a fresh
	// row instead of being a no-op. Re-enabling a disabled-then-regranted
	// rule is handled explicitly via UpdatePermissionEnabled, not here.
	CreateSessionPermission(ctx context.Context, arg CreateSessionPermissionParams) error
	DeleteFile(ctx context.Context, id string) error
	DeleteMessage(ctx context.Context, id string) error
	DeletePendingInject(ctx context.Context, id string) error
	DeletePermission(ctx context.Context, id string) error
	DeleteSession(ctx context.Context, id string) error
	DeleteSessionFiles(ctx context.Context, sessionID string) error
	DeleteSessionMessages(ctx context.Context, sessionID string) error
	EnqueueRunQueueEntry(ctx context.Context, arg EnqueueRunQueueEntryParams) (SessionRunQueue, error)
	GetAverageResponseTime(ctx context.Context) (int64, error)
	// call_tree_activity.sql: freshest message activity across a session's whole
	// descendant call tree (root + every sub-agent session reachable via
	// parent_session_id), in ONE recursive-CTE query per root.
	//
	// Bounded vs. unbounded:
	//   * DEPTH is capped: the recursive member carries `tree.depth < 511`, so a
	//     pathological deep chain (or an accidental parent/child cycle) can never
	//     recurse indefinitely (see TestGetCallTreeActivity_DepthGuard).
	//   * WIDTH (fan-out) is NOT bounded by row count. A single root with many
	//     direct children produces that many rows in the CTE regardless of depth.
	//     This is a deliberate, documented choice, not an oversight: SQLite's
	//     recursive CTE cannot bound the TOTAL number of materialized rows -- the
	//     recursive member only sees the PREVIOUS iteration's working table, never
	//     the accumulated set, so a running "rows visited" counter is not
	//     expressible in the recursion, and SQLite does not support LIMIT inside
	//     the recursive member. Bounding fan-out would therefore require either
	//     abandoning this SQL CTE (the SQL form replaced the Go BFS in task #104)
	//     or reverting to a Go-side BFS, neither of which is warranted: in
	//     practice a parent session spawns at most a handful of concurrent
	//     sub-agent delegations, so unbounded fan-out is not a real performance
	//     risk. The single-root form also ends in LIMIT 1 and the batch form in a
	//     per-root ROW_NUMBER()=1 filter, so only one row per root ever leaves
	//     the query.
	GetCallTreeActivity(ctx context.Context, id string) (GetCallTreeActivityRow, error)
	GetCallTreeActivityBatch(ctx context.Context, rootIds []string) ([]GetCallTreeActivityBatchRow, error)
	GetFile(ctx context.Context, id string) (File, error)
	GetFileByPathAndSession(ctx context.Context, arg GetFileByPathAndSessionParams) (File, error)
	GetFileRead(ctx context.Context, arg GetFileReadParams) (ReadFile, error)
	GetHourDayHeatmap(ctx context.Context) ([]GetHourDayHeatmapRow, error)
	GetLastSession(ctx context.Context) (Session, error)
	GetMessage(ctx context.Context, id string) (Message, error)
	// Get the oldest pending entry for a session (for transactional lease).
	GetOldestPendingRunQueueEntryForSession(ctx context.Context, sessionID string) (SessionRunQueue, error)
	GetRecentActivity(ctx context.Context) ([]GetRecentActivityRow, error)
	// Get a single entry by ID.
	GetRunQueueEntry(ctx context.Context, id string) (SessionRunQueue, error)
	GetSessionByID(ctx context.Context, id string) (Session, error)
	// Returns the child's current cost and the amount already charged to the
	// parent (parent_cost_accounted). Used by TransferChildCostToParent inside
	// a transaction so delta = cost - accounted is computed from a single
	// consistent read within that transaction.
	GetSessionCostAccounting(ctx context.Context, id string) (GetSessionCostAccountingRow, error)
	GetToolUsage(ctx context.Context) ([]GetToolUsageRow, error)
	GetTotalStats(ctx context.Context) (GetTotalStatsRow, error)
	// Returns, in a SINGLE round trip, the (created_at, rowid) of the row at
	// `offset` positions back from the newest message in the session, together
	// with the session's total message count as of that same statement
	// execution (SQLite evaluates COUNT(*) OVER() over the full WHERE-matched row
	// set before LIMIT/OFFSET are applied, in the same query plan as the LIMIT 1
	// OFFSET ? row selection - both numbers come from one consistent snapshot).
	//
	// This is the fix for the cross-statement race in read_delegation_transcript.go:
	// previously Count() and ListPaginated() were two independent queries, so a
	// message inserted between them (the normal case while observing a live
	// sub-agent) could make the total and the offset-derived window disagree.
	// message.Service.ListPaginatedSnapshot calls this query FIRST to pin down a
	// single high-water-mark snapshot (the boundary row's created_at/row_id, plus
	// total), then fetches the window strictly at-or-before that boundary via
	// ListMessagesBySessionOlderThanCreatedAt + ListMessagesBySessionAtCreatedAt.
	// Any message inserted after this query executes is newer than the pinned
	// boundary and is therefore correctly excluded from both the "total" figure
	// and the follow-up window fetch - the read as a whole reflects one
	// consistent point in time rather than drifting across separate round trips.
	//
	// created_at/row_id are NULL when offset falls at or past the end of the
	// session's messages (i.e. there is no row at that position): callers must
	// treat NULL as "start of history", matching offset's existing clamp-to-empty
	// behavior in clampTranscriptWindow.
	//
	// row_id is exposed via CAST(rowid AS INTEGER): sqlc's SQLite catalog has no
	// notion of SQLite's implicit rowid column outside ORDER BY (confirmed by
	// hand: any bare `rowid` reference in a WHERE clause or plain SELECT-list
	// position fails static analysis with "column \"rowid\" does not exist",
	// while the identical reference wrapped in CAST(... AS INTEGER) in the
	// SELECT list is accepted) - see ListMessagesBySessionOlderThanCreatedAt's
	// comment for why the keyset filter itself therefore avoids rowid in a WHERE
	// clause entirely rather than fighting this further.
	GetTranscriptWindowCursor(ctx context.Context, arg GetTranscriptWindowCursorParams) (GetTranscriptWindowCursorRow, error)
	GetUsageByDay(ctx context.Context) ([]GetUsageByDayRow, error)
	GetUsageByDayOfWeek(ctx context.Context) ([]GetUsageByDayOfWeekRow, error)
	GetUsageByHour(ctx context.Context) ([]GetUsageByHourRow, error)
	GetUsageByModel(ctx context.Context) ([]GetUsageByModelRow, error)
	// Atomic additive update for session cost. Safe under fan-out (multiple
	// sub-agent goroutines finishing concurrently and each charging the
	// parent) and across processes (orchestrator with parallel crush runs).
	// Returns the updated row so the caller can refresh its snapshot.
	IncrementSessionCost(ctx context.Context, arg IncrementSessionCostParams) (Session, error)
	// Claim a specific entry by ID (call after GetOldestPendingRunQueueEntryForSession in a transaction).
	// Does not increment attempts: leasing only claims the row for execution.
	// NackRunQueueEntry and CleanupExpiredLeases are the only sites that count
	// an attempt, exactly once per completed failed execution or per lease
	// recovered from a crashed/hung executor. Counting here too, in addition to
	// NackRunQueueEntry, double-counted every failure cycle, silently halving
	// the effective value of RunQueueMaxAttempts.
	LeaseRunQueueEntryByID(ctx context.Context, arg LeaseRunQueueEntryByIDParams) (SessionRunQueue, error)
	ListAllSessionPermissions(ctx context.Context) ([]SessionPermission, error)
	// Returns every session including children (no parent_session_id filter).
	// Used by sessions gc to enumerate all sessions for garbage collection.
	ListAllSessions(ctx context.Context) ([]Session, error)
	// rowid is the tie-breaker: see ListUserMessagesBySession above - identical
	// reasoning applies across all sessions, not just one.
	ListAllUserMessages(ctx context.Context) ([]Message, error)
	ListFilesByPath(ctx context.Context, path string) ([]File, error)
	ListFilesBySession(ctx context.Context, sessionID string) ([]File, error)
	ListLatestSessionFiles(ctx context.Context, sessionID string) ([]File, error)
	// rowid is the tie-breaker: created_at is stored in SECONDS, so a single agent
	// turn produces dozens of rows with an identical created_at. Without a total
	// order SQLite does not guarantee a stable order among those ties. This is the
	// same class of bug fixed for ListMessagesBySessionPaginated (see its comment
	// below) - here applied to the oldest-first, non-paginated variant, so
	// (created_at ASC, rowid ASC) is a deterministic oldest-first total order.
	// rowid is SQLite's implicit monotonic insertion counter (messages.id is a
	// non-monotonic UUID, unsuitable as a tiebreaker).
	ListMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	// Second half of the keyset pagination pair (see
	// ListMessagesBySessionOlderThanCreatedAt): returns every message in the
	// session sharing the exact boundary second, WITH its rowid (via
	// CAST(rowid AS INTEGER), the one position sqlc's SQLite catalog accepts a
	// bare rowid reference in - see GetTranscriptWindowCursor's comment), so the
	// Go caller can apply the `rowid < boundary_row_id` half of the tiebreaker
	// itself and merge the result with the older-seconds query above into one
	// deterministic (created_at DESC, rowid DESC) window.
	ListMessagesBySessionAtCreatedAt(ctx context.Context, arg ListMessagesBySessionAtCreatedAtParams) ([]ListMessagesBySessionAtCreatedAtRow, error)
	// First half of the keyset pagination pair used by
	// read_delegation_transcript.go: returns messages strictly OLDER (by
	// created_at second) than the cursor boundary, deterministically ordered.
	// Combined in Go with ListMessagesBySessionAtCreatedAt (which handles the
	// boundary second's exact-tie rows via the rowid tiebreaker) to reproduce the
	// same (created_at, rowid) keyset semantics as a single
	// `(created_at, rowid) < (?, ?)` comparison would, without needing rowid in a
	// WHERE clause - see GetTranscriptWindowCursor's comment for why that's
	// avoided. Because the boundary is a concrete value pinned by
	// GetTranscriptWindowCursor at the start of the read (not "the Nth row from
	// the current end"), inserting new messages at the head between calls can
	// never shift which rows this query returns: the boundary itself doesn't move.
	ListMessagesBySessionOlderThanCreatedAt(ctx context.Context, arg ListMessagesBySessionOlderThanCreatedAtParams) ([]Message, error)
	// rowid is the tie-breaker: created_at is stored in SECONDS, so a single agent
	// turn produces dozens of rows with an identical created_at. Without a total
	// order SQLite does not guarantee a stable order among those ties, which makes
	// OFFSET pagination lose/duplicate rows when the query plan shifts between
	// page fetches. rowid is SQLite's implicit monotonic insertion counter, so
	// (created_at DESC, rowid DESC) is a deterministic newest-first total order.
	//
	// NOTE: plain OFFSET is still vulnerable to a DIFFERENT instability than the
	// tie-breaker bug above: concurrent inserts at the head of the DESC order (new
	// messages from a still-running delegation) shift what a given numeric offset
	// points at between two separate calls of this query. This query remains here
	// as the plain, unprotected primitive; message.Service.ListPaginatedSnapshot
	// is the race-free caller-facing wrapper read_delegation_transcript.go
	// actually uses, built from GetTranscriptWindowCursor (pins one consistent
	// snapshot boundary) plus the keyset pair ListMessagesBySessionOlderThan-
	// CreatedAt / ListMessagesBySessionAtCreatedAt (fetches the window strictly
	// at-or-before that boundary, immune to head insertions by construction).
	ListMessagesBySessionPaginated(ctx context.Context, arg ListMessagesBySessionPaginatedParams) ([]Message, error)
	ListNewFiles(ctx context.Context) ([]File, error)
	ListPendingInjectsBySession(ctx context.Context, sessionID string) ([]PendingInject, error)
	// Get all pending entries (for pump scanning across all sessions).
	ListPendingRunQueueEntries(ctx context.Context) ([]SessionRunQueue, error)
	ListSessionPermissions(ctx context.Context, sessionID string) ([]SessionPermission, error)
	ListSessionReadFiles(ctx context.Context, sessionID string) ([]ReadFile, error)
	ListSessions(ctx context.Context) ([]Session, error)
	// Get all leased entries with expired leases (for pump lease recovery).
	ListStaleLeasedRunQueueEntries(ctx context.Context, leaseExpiresAt sql.NullInt64) ([]SessionRunQueue, error)
	// Returns every session whose parent_session_id matches the argument,
	// ordered oldest-first so callers reconstructing a fan-out get the
	// sub-agent results in dispatch order.
	ListSubSessions(ctx context.Context, parentSessionID sql.NullString) ([]Session, error)
	// rowid is the tie-breaker: created_at is stored in SECONDS, so multiple user
	// messages within the same second (e.g. rapid follow-ups) are not given a
	// stable order by created_at alone. Same class of bug fixed for
	// ListMessagesBySession/ListMessagesBySessionPaginated - rowid is SQLite's
	// implicit monotonic insertion counter (messages.id is a non-monotonic UUID,
	// unsuitable as a tiebreaker), so (created_at DESC, rowid DESC) is a
	// deterministic newest-first total order.
	ListUserMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	// Returns the row id of an enabled "always allow" rule that matches the
	// given (sessionID, toolName, action, path) tuple, or sql.ErrNoRows.
	// session_id is empty for global rules; we accept either empty or the
	// exact session_id so the same query handles both.
	MatchSessionPermission(ctx context.Context, arg MatchSessionPermissionParams) (string, error)
	// Release a leased entry back to pending state (non-terminal failure, retry later).
	// Increments attempts but does NOT set terminal_failure.
	// Scoped to the current lease owner, same as AckRunQueueEntry.
	NackRunQueueEntry(ctx context.Context, arg NackRunQueueEntryParams) (SessionRunQueue, error)
	// Release a leased entry back to pending state without counting it as an
	// attempt. Used specifically for session.SessionLockBusyError: another live
	// process legitimately holding the OS session lock is routine, expected
	// contention, not a failure of the call itself, and must never count toward
	// RunQueueMaxAttempts. Without this, the durable queue would delete
	// accepted user work after nothing more than a few turns of ordinary lock
	// contention. Also used for the ErrCallQueuedNotExecuted backoff path and
	// for releasing a mismatched attempts-exhausted lease unharmed.
	// Scoped to the current lease owner, same as AckRunQueueEntry.
	NackRunQueueEntryNoAttemptPenalty(ctx context.Context, arg NackRunQueueEntryNoAttemptPenaltyParams) (SessionRunQueue, error)
	RecordFileRead(ctx context.Context, arg RecordFileReadParams) error
	RenameSession(ctx context.Context, arg RenameSessionParams) error
	// Extend a lease expiry while its owner is still genuinely working on it,
	// or to back off a lease without counting a failed attempt. Scoped to
	// status = leased AND leased_by = ? so a lease already reassigned to a
	// different owner (this owner lost the race to a prior CleanupExpiredLeases
	// recovery) is never silently extended out from under the new owner:
	// execrows reports 0 rows in that case, which the caller must treat as
	// meaning it is no longer this executor's lease to keep alive.
	RenewRunQueueLease(ctx context.Context, arg RenewRunQueueLeaseParams) (int64, error)
	// Marks the child's full current cost as charged to the parent, so the
	// next TransferChildCostToParent call charges only new cost accrued above
	// this point. Run inside the same transaction as the parent's
	// IncrementSessionCost so a crash between the two cannot leave the parent
	// charged but the child's accounting lagging (or vice versa).
	SetParentCostAccounted(ctx context.Context, arg SetParentCostAccountedParams) error
	// Mark a leased entry as terminal failure (no retry, even if attempts < max).
	// Used for ErrCallAlreadyAttempted-type errors where retry would cause duplicates.
	// Scoped to the current lease owner, same as AckRunQueueEntry.
	TerminalFailRunQueueEntry(ctx context.Context, arg TerminalFailRunQueueEntryParams) (string, error)
	UpdateMessage(ctx context.Context, arg UpdateMessageParams) error
	UpdateMessagePinned(ctx context.Context, arg UpdateMessagePinnedParams) error
	UpdatePermissionEnabled(ctx context.Context, arg UpdatePermissionEnabledParams) error
	UpdateSessionModels(ctx context.Context, arg UpdateSessionModelsParams) error
	UpdateSessionReasoningEffort(ctx context.Context, arg UpdateSessionReasoningEffortParams) error
	UpdateSessionSystemPrompt(ctx context.Context, arg UpdateSessionSystemPromptParams) error
}

var _ Querier = (*Queries)(nil)
