// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountMessagesBySession(ctx context.Context, sessionID string) (int64, error)
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	// pending_injects is the cross-process inject queue for `crush sessions
	// inject`. See migration 20260703000001 for the full semantics.
	//
	// NOTE: as of this fork the session-layer wrapper (session.go
	// DrainPendingInjects / CreatePendingInject) talks to this table via raw
	// database/sql, matching the existing cross-process signal pattern
	// (RequestCancel / SetBudget). These sqlc-generated methods below ARE
	// wired into db.go's Prepare/Close/WithTx (as of the sqlc regeneration
	// that added call_tree_activity.sql), but nothing in the codebase calls
	// them yet - session.go's raw-SQL path remains the actual implementation.
	// Keep both in sync if pending_injects' schema changes.
	CreatePendingInject(ctx context.Context, arg CreatePendingInjectParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// ON CONFLICT DO NOTHING relies on idx_session_permissions_uniq from
	// migration 20260517000001. Without it a repeated Always-Allow click
	// on the same (session, tool, action, path) tuple would create a fresh
	// row instead of being a no-op. Re-enabling a disabled-then-regranted
	// rule is handled explicitly via UpdatePermissionEnabled, not here.
	CreateSessionPermission(ctx context.Context, arg CreateSessionPermissionParams) error
	DeleteFile(ctx context.Context, id string) error
	DeleteMessage(ctx context.Context, id string) error
	DeletePendingInject(ctx context.Context, id string) error
	DeletePermission(ctx context.Context, id string) error
	DeleteSession(ctx context.Context, id string) error
	DeleteSessionFiles(ctx context.Context, sessionID string) error
	DeleteSessionMessages(ctx context.Context, sessionID string) error
	GetAverageResponseTime(ctx context.Context) (int64, error)
	// call_tree_activity.sql: freshest message activity across a session's whole
	// descendant call tree (root + every sub-agent session reachable via
	// parent_session_id), in ONE recursive-CTE query per root.
	//
	// Bounded vs. unbounded:
	//   * DEPTH is capped: the recursive member carries `tree.depth < 511`, so a
	//     pathological deep chain (or an accidental parent/child cycle) can never
	//     recurse indefinitely (see TestGetCallTreeActivity_DepthGuard).
	//   * WIDTH (fan-out) is NOT bounded by row count. A single root with many
	//     direct children produces that many rows in the CTE regardless of depth.
	//     This is a deliberate, documented choice, not an oversight: SQLite's
	//     recursive CTE cannot bound the TOTAL number of materialized rows -- the
	//     recursive member only sees the PREVIOUS iteration's working table, never
	//     the accumulated set, so a running "rows visited" counter is not
	//     expressible in the recursion, and SQLite does not support LIMIT inside
	//     the recursive member. Bounding fan-out would therefore require either
	//     abandoning this SQL CTE (the SQL form replaced the Go BFS in task #104)
	//     or reverting to a Go-side BFS, neither of which is warranted: in
	//     practice a parent session spawns at most a handful of concurrent
	//     sub-agent delegations, so unbounded fan-out is not a real performance
	//     risk. The single-root form also ends in LIMIT 1 and the batch form in a
	//     per-root ROW_NUMBER()=1 filter, so only one row per root ever leaves
	//     the query.
	GetCallTreeActivity(ctx context.Context, id string) (GetCallTreeActivityRow, error)
	GetCallTreeActivityBatch(ctx context.Context, rootIds []string) ([]GetCallTreeActivityBatchRow, error)
	GetFile(ctx context.Context, id string) (File, error)
	GetFileByPathAndSession(ctx context.Context, arg GetFileByPathAndSessionParams) (File, error)
	GetFileRead(ctx context.Context, arg GetFileReadParams) (ReadFile, error)
	GetHourDayHeatmap(ctx context.Context) ([]GetHourDayHeatmapRow, error)
	GetLastSession(ctx context.Context) (Session, error)
	GetMessage(ctx context.Context, id string) (Message, error)
	GetRecentActivity(ctx context.Context) ([]GetRecentActivityRow, error)
	GetSessionByID(ctx context.Context, id string) (Session, error)
	// Returns the child's current cost and the amount already charged to the
	// parent (parent_cost_accounted). Used by TransferChildCostToParent inside
	// a transaction so delta = cost - accounted is computed from a single
	// consistent read within that transaction.
	GetSessionCostAccounting(ctx context.Context, id string) (GetSessionCostAccountingRow, error)
	GetToolUsage(ctx context.Context) ([]GetToolUsageRow, error)
	GetTotalStats(ctx context.Context) (GetTotalStatsRow, error)
	GetUsageByDay(ctx context.Context) ([]GetUsageByDayRow, error)
	GetUsageByDayOfWeek(ctx context.Context) ([]GetUsageByDayOfWeekRow, error)
	GetUsageByHour(ctx context.Context) ([]GetUsageByHourRow, error)
	GetUsageByModel(ctx context.Context) ([]GetUsageByModelRow, error)
	// Atomic additive update for session cost. Safe under fan-out (multiple
	// sub-agent goroutines finishing concurrently and each charging the
	// parent) and across processes (orchestrator with parallel crush runs).
	// Returns the updated row so the caller can refresh its snapshot.
	IncrementSessionCost(ctx context.Context, arg IncrementSessionCostParams) (Session, error)
	ListAllSessionPermissions(ctx context.Context) ([]SessionPermission, error)
	// Returns every session including children (no parent_session_id filter).
	// Used by sessions gc to enumerate all sessions for garbage collection.
	ListAllSessions(ctx context.Context) ([]Session, error)
	// rowid is the tie-breaker: see ListUserMessagesBySession above - identical
	// reasoning applies across all sessions, not just one.
	ListAllUserMessages(ctx context.Context) ([]Message, error)
	ListFilesByPath(ctx context.Context, path string) ([]File, error)
	ListFilesBySession(ctx context.Context, sessionID string) ([]File, error)
	ListLatestSessionFiles(ctx context.Context, sessionID string) ([]File, error)
	// rowid is the tie-breaker: created_at is stored in SECONDS, so a single agent
	// turn produces dozens of rows with an identical created_at. Without a total
	// order SQLite does not guarantee a stable order among those ties. This is the
	// same class of bug fixed for ListMessagesBySessionPaginated (see its comment
	// below) - here applied to the oldest-first, non-paginated variant, so
	// (created_at ASC, rowid ASC) is a deterministic oldest-first total order.
	// rowid is SQLite's implicit monotonic insertion counter (messages.id is a
	// non-monotonic UUID, unsuitable as a tiebreaker).
	ListMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	// rowid is the tie-breaker: created_at is stored in SECONDS, so a single agent
	// turn produces dozens of rows with an identical created_at. Without a total
	// order SQLite does not guarantee a stable order among those ties, which makes
	// OFFSET pagination lose/duplicate rows when the query plan shifts between
	// page fetches. rowid is SQLite's implicit monotonic insertion counter, so
	// (created_at DESC, rowid DESC) is a deterministic newest-first total order.
	ListMessagesBySessionPaginated(ctx context.Context, arg ListMessagesBySessionPaginatedParams) ([]Message, error)
	ListNewFiles(ctx context.Context) ([]File, error)
	ListPendingInjectsBySession(ctx context.Context, sessionID string) ([]PendingInject, error)
	ListSessionPermissions(ctx context.Context, sessionID string) ([]SessionPermission, error)
	ListSessionReadFiles(ctx context.Context, sessionID string) ([]ReadFile, error)
	ListSessions(ctx context.Context) ([]Session, error)
	// Returns every session whose parent_session_id matches the argument,
	// ordered oldest-first so callers reconstructing a fan-out get the
	// sub-agent results in dispatch order.
	ListSubSessions(ctx context.Context, parentSessionID sql.NullString) ([]Session, error)
	// rowid is the tie-breaker: created_at is stored in SECONDS, so multiple user
	// messages within the same second (e.g. rapid follow-ups) are not given a
	// stable order by created_at alone. Same class of bug fixed for
	// ListMessagesBySession/ListMessagesBySessionPaginated - rowid is SQLite's
	// implicit monotonic insertion counter (messages.id is a non-monotonic UUID,
	// unsuitable as a tiebreaker), so (created_at DESC, rowid DESC) is a
	// deterministic newest-first total order.
	ListUserMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	// Returns the row id of an enabled "always allow" rule that matches the
	// given (sessionID, toolName, action, path) tuple, or sql.ErrNoRows.
	// session_id is empty for global rules; we accept either empty or the
	// exact session_id so the same query handles both.
	MatchSessionPermission(ctx context.Context, arg MatchSessionPermissionParams) (string, error)
	RecordFileRead(ctx context.Context, arg RecordFileReadParams) error
	RenameSession(ctx context.Context, arg RenameSessionParams) error
	// Marks the child's full current cost as charged to the parent, so the
	// next TransferChildCostToParent call charges only new cost accrued above
	// this point. Run inside the same transaction as the parent's
	// IncrementSessionCost so a crash between the two cannot leave the parent
	// charged but the child's accounting lagging (or vice versa).
	SetParentCostAccounted(ctx context.Context, arg SetParentCostAccountedParams) error
	UpdateMessage(ctx context.Context, arg UpdateMessageParams) error
	UpdateMessagePinned(ctx context.Context, arg UpdateMessagePinnedParams) error
	UpdatePermissionEnabled(ctx context.Context, arg UpdatePermissionEnabledParams) error
	UpdateSessionModels(ctx context.Context, arg UpdateSessionModelsParams) error
	UpdateSessionReasoningEffort(ctx context.Context, arg UpdateSessionReasoningEffortParams) error
	UpdateSessionSystemPrompt(ctx context.Context, arg UpdateSessionSystemPromptParams) error
	UpdateSessionTitleAndUsage(ctx context.Context, arg UpdateSessionTitleAndUsageParams) error
}

var _ Querier = (*Queries)(nil)
