// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
	"database/sql"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    id,
    parent_session_id,
    title,
    message_count,
    prompt_tokens,
    completion_tokens,
    cost,
    summary_message_id,
    updated_at,
    created_at,
    large_model_provider,
    large_model_id,
    small_model_provider,
    small_model_id,
    yolo_enabled
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    null,
    strftime('%s', 'now'),
    strftime('%s', 'now'),
    ?,
    ?,
    ?,
    ?,
    0
) RETURNING id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, todos, large_model_provider, large_model_id, small_model_provider, small_model_id, system_prompt, yolo_enabled, large_model_reasoning_effort, small_model_reasoning_effort
`

type CreateSessionParams struct {
	ID                 string         `json:"id"`
	ParentSessionID    sql.NullString `json:"parent_session_id"`
	Title              string         `json:"title"`
	MessageCount       int64          `json:"message_count"`
	PromptTokens       int64          `json:"prompt_tokens"`
	CompletionTokens   int64          `json:"completion_tokens"`
	Cost               float64        `json:"cost"`
	LargeModelProvider sql.NullString `json:"large_model_provider"`
	LargeModelID       sql.NullString `json:"large_model_id"`
	SmallModelProvider sql.NullString `json:"small_model_provider"`
	SmallModelID       sql.NullString `json:"small_model_id"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.queryRow(ctx, q.createSessionStmt, createSession,
		arg.ID,
		arg.ParentSessionID,
		arg.Title,
		arg.MessageCount,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.Cost,
		arg.LargeModelProvider,
		arg.LargeModelID,
		arg.SmallModelProvider,
		arg.SmallModelID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.MessageCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.SummaryMessageID,
		&i.Todos,
		&i.LargeModelProvider,
		&i.LargeModelID,
		&i.SmallModelProvider,
		&i.SmallModelID,
		&i.SystemPrompt,
		&i.YoloEnabled,
		&i.LargeModelReasoningEffort,
		&i.SmallModelReasoningEffort,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteSessionStmt, deleteSession, id)
	return err
}

const getLastSession = `-- name: GetLastSession :one
SELECT id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, todos, large_model_provider, large_model_id, small_model_provider, small_model_id, system_prompt, yolo_enabled, large_model_reasoning_effort, small_model_reasoning_effort
FROM sessions
ORDER BY updated_at DESC
LIMIT 1
`

func (q *Queries) GetLastSession(ctx context.Context) (Session, error) {
	row := q.queryRow(ctx, q.getLastSessionStmt, getLastSession)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.MessageCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.SummaryMessageID,
		&i.Todos,
		&i.LargeModelProvider,
		&i.LargeModelID,
		&i.SmallModelProvider,
		&i.SmallModelID,
		&i.SystemPrompt,
		&i.YoloEnabled,
		&i.LargeModelReasoningEffort,
		&i.SmallModelReasoningEffort,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, todos, large_model_provider, large_model_id, small_model_provider, small_model_id, system_prompt, yolo_enabled, large_model_reasoning_effort, small_model_reasoning_effort
FROM sessions
WHERE id = ? LIMIT 1
`

func (q *Queries) GetSessionByID(ctx context.Context, id string) (Session, error) {
	row := q.queryRow(ctx, q.getSessionByIDStmt, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.MessageCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.SummaryMessageID,
		&i.Todos,
		&i.LargeModelProvider,
		&i.LargeModelID,
		&i.SmallModelProvider,
		&i.SmallModelID,
		&i.SystemPrompt,
		&i.YoloEnabled,
		&i.LargeModelReasoningEffort,
		&i.SmallModelReasoningEffort,
	)
	return i, err
}

const incrementSessionCost = `-- name: IncrementSessionCost :one
UPDATE sessions
SET
    cost = cost + ?,
    updated_at = strftime('%s', 'now')
WHERE id = ?
RETURNING id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, todos, large_model_provider, large_model_id, small_model_provider, small_model_id, system_prompt, yolo_enabled, large_model_reasoning_effort, small_model_reasoning_effort
`

type IncrementSessionCostParams struct {
	Cost float64 `json:"cost"`
	ID   string  `json:"id"`
}

// Atomic additive update for session cost. Safe under fan-out (multiple
// sub-agent goroutines finishing concurrently and each charging the
// parent) and across processes (orchestrator with parallel crush runs).
// Returns the updated row so the caller can refresh its snapshot.
func (q *Queries) IncrementSessionCost(ctx context.Context, arg IncrementSessionCostParams) (Session, error) {
	row := q.queryRow(ctx, q.incrementSessionCostStmt, incrementSessionCost, arg.Cost, arg.ID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.MessageCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.SummaryMessageID,
		&i.Todos,
		&i.LargeModelProvider,
		&i.LargeModelID,
		&i.SmallModelProvider,
		&i.SmallModelID,
		&i.SystemPrompt,
		&i.YoloEnabled,
		&i.LargeModelReasoningEffort,
		&i.SmallModelReasoningEffort,
	)
	return i, err
}

const listSessions = `-- name: ListSessions :many
SELECT id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, todos, large_model_provider, large_model_id, small_model_provider, small_model_id, system_prompt, yolo_enabled, large_model_reasoning_effort, small_model_reasoning_effort
FROM sessions
WHERE parent_session_id is NULL
ORDER BY updated_at DESC
`

func (q *Queries) ListSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.query(ctx, q.listSessionsStmt, listSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ParentSessionID,
			&i.Title,
			&i.MessageCount,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.Cost,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.SummaryMessageID,
			&i.Todos,
			&i.LargeModelProvider,
			&i.LargeModelID,
			&i.SmallModelProvider,
			&i.SmallModelID,
			&i.SystemPrompt,
			&i.YoloEnabled,
			&i.LargeModelReasoningEffort,
			&i.SmallModelReasoningEffort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameSession = `-- name: RenameSession :exec
UPDATE sessions
SET
    title = ?
WHERE id = ?
`

type RenameSessionParams struct {
	Title string `json:"title"`
	ID    string `json:"id"`
}

func (q *Queries) RenameSession(ctx context.Context, arg RenameSessionParams) error {
	_, err := q.exec(ctx, q.renameSessionStmt, renameSession, arg.Title, arg.ID)
	return err
}

const setSessionYolo = `-- name: SetSessionYolo :exec
UPDATE sessions
SET yolo_enabled = ?,
    updated_at = strftime('%s', 'now')
WHERE id = ?
`

type SetSessionYoloParams struct {
	YoloEnabled int64  `json:"yolo_enabled"`
	ID          string `json:"id"`
}

func (q *Queries) SetSessionYolo(ctx context.Context, arg SetSessionYoloParams) error {
	_, err := q.exec(ctx, q.setSessionYoloStmt, setSessionYolo, arg.YoloEnabled, arg.ID)
	return err
}

const updateSession = `-- name: UpdateSession :one
UPDATE sessions
SET
    title = ?,
    prompt_tokens = ?,
    completion_tokens = ?,
    summary_message_id = ?,
    todos = ?,
    updated_at = strftime('%s', 'now')
WHERE id = ?
RETURNING id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, todos, large_model_provider, large_model_id, small_model_provider, small_model_id, system_prompt, yolo_enabled, large_model_reasoning_effort, small_model_reasoning_effort
`

type UpdateSessionParams struct {
	Title            string         `json:"title"`
	PromptTokens     int64          `json:"prompt_tokens"`
	CompletionTokens int64          `json:"completion_tokens"`
	SummaryMessageID sql.NullString `json:"summary_message_id"`
	Todos            sql.NullString `json:"todos"`
	ID               string         `json:"id"`
}

// Overwrites title/prompt_tokens/completion_tokens/summary/todos but NOT
// cost. Cost is mutated only via IncrementSessionCost so concurrent
// sub-agent goroutines (and parallel crush processes that ever share a
// session) cannot lose accrued cost via read-modify-write.
func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error) {
	row := q.queryRow(ctx, q.updateSessionStmt, updateSession,
		arg.Title,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.SummaryMessageID,
		arg.Todos,
		arg.ID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.MessageCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.SummaryMessageID,
		&i.Todos,
		&i.LargeModelProvider,
		&i.LargeModelID,
		&i.SmallModelProvider,
		&i.SmallModelID,
		&i.SystemPrompt,
		&i.YoloEnabled,
		&i.LargeModelReasoningEffort,
		&i.SmallModelReasoningEffort,
	)
	return i, err
}

const updateSessionModels = `-- name: UpdateSessionModels :exec
UPDATE sessions
SET
    large_model_provider = ?,
    large_model_id = ?,
    small_model_provider = ?,
    small_model_id = ?,
    updated_at = strftime('%s', 'now')
WHERE id = ?
`

type UpdateSessionModelsParams struct {
	LargeModelProvider sql.NullString `json:"large_model_provider"`
	LargeModelID       sql.NullString `json:"large_model_id"`
	SmallModelProvider sql.NullString `json:"small_model_provider"`
	SmallModelID       sql.NullString `json:"small_model_id"`
	ID                 string         `json:"id"`
}

func (q *Queries) UpdateSessionModels(ctx context.Context, arg UpdateSessionModelsParams) error {
	_, err := q.exec(ctx, q.updateSessionModelsStmt, updateSessionModels,
		arg.LargeModelProvider,
		arg.LargeModelID,
		arg.SmallModelProvider,
		arg.SmallModelID,
		arg.ID,
	)
	return err
}

const updateSessionReasoningEffort = `-- name: UpdateSessionReasoningEffort :exec
UPDATE sessions
SET
    large_model_reasoning_effort = ?,
    small_model_reasoning_effort = ?,
    updated_at = strftime('%s', 'now')
WHERE id = ?
`

type UpdateSessionReasoningEffortParams struct {
	LargeModelReasoningEffort sql.NullString `json:"large_model_reasoning_effort"`
	SmallModelReasoningEffort sql.NullString `json:"small_model_reasoning_effort"`
	ID                        string         `json:"id"`
}

func (q *Queries) UpdateSessionReasoningEffort(ctx context.Context, arg UpdateSessionReasoningEffortParams) error {
	_, err := q.exec(ctx, q.updateSessionReasoningEffortStmt, updateSessionReasoningEffort, arg.LargeModelReasoningEffort, arg.SmallModelReasoningEffort, arg.ID)
	return err
}

const updateSessionSystemPrompt = `-- name: UpdateSessionSystemPrompt :exec
UPDATE sessions
SET
    system_prompt = ?,
    updated_at = strftime('%s', 'now')
WHERE id = ?
`

type UpdateSessionSystemPromptParams struct {
	SystemPrompt string `json:"system_prompt"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateSessionSystemPrompt(ctx context.Context, arg UpdateSessionSystemPromptParams) error {
	_, err := q.exec(ctx, q.updateSessionSystemPromptStmt, updateSessionSystemPrompt, arg.SystemPrompt, arg.ID)
	return err
}

const updateSessionTitleAndUsage = `-- name: UpdateSessionTitleAndUsage :exec
UPDATE sessions
SET
    title = ?,
    prompt_tokens = prompt_tokens + ?,
    completion_tokens = completion_tokens + ?,
    cost = cost + ?,
    updated_at = strftime('%s', 'now')
WHERE id = ?
`

type UpdateSessionTitleAndUsageParams struct {
	Title            string  `json:"title"`
	PromptTokens     int64   `json:"prompt_tokens"`
	CompletionTokens int64   `json:"completion_tokens"`
	Cost             float64 `json:"cost"`
	ID               string  `json:"id"`
}

func (q *Queries) UpdateSessionTitleAndUsage(ctx context.Context, arg UpdateSessionTitleAndUsageParams) error {
	_, err := q.exec(ctx, q.updateSessionTitleAndUsageStmt, updateSessionTitleAndUsage,
		arg.Title,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.Cost,
		arg.ID,
	)
	return err
}
